addSbtPlugin("com.github.sbt"   % "sbt-github-actions" % "0.31.0")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"       % "0.5.7")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"        % "0.6.4")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"       % "2.6.1")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"       % "0.14.7")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"     % "1.12.0")
